### ISSUE TITLE
New release with MOI 0.3 support

### ISSUE THREAD

**Issue by tkoolen** [oxfordcontrol/OSQP.jl#15]
I can draft a new release later today. @bstellato, let me know if you want me to wait.

**Comment by bstellato** [comment]
Sounds good! Thank you for the PR before. I have not followed up the latest changes in MOI. You are more familiar than me on that. Please update the `CHANGELOG.md` file with what changed so that we can keep track of it. 

I am working on some Python packaging issues at the moment and on the `0.3.1` release. Nothing should change from the Julia interface though. Only 0.x releases will change the interface commands and I will take care/let you know about them.

**Comment by tkoolen** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/15070

**Comment by bstellato** [comment]
Fantastic! Thanks a lot. `0.1.5` version number sounds good.
